import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTZl6mc4gPy_BqEI3RQE9-cjSWcQrAqjU',
    appId: '1:929948239768:web:701cd9a89f38a4268c4ded',
    messagingSenderId: '929948239768',
    projectId: 'prepschedule',
    authDomain: 'prepschedule.firebaseapp.com',
    storageBucket: 'prepschedule.firebasestorage.app',
    measurementId: 'G-R95MWHRPMQ',
  );

  // Note: Android and iOS configurations are placeholders. 
  // Normally these are generated by the CLI, but since we are doing it manually, 
  // you might need to add your Android/iOS specific keys here if they differ.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIza...', // Placeholder
    appId: '...',      // Placeholder
    messagingSenderId: '929948239768',
    projectId: 'prepschedule',
    storageBucket: 'prepschedule.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIza...', // Placeholder
    appId: '...',      // Placeholder
    messagingSenderId: '929948239768',
    projectId: 'prepschedule',
    storageBucket: 'prepschedule.firebasestorage.app',
    iosBundleId: 'com.example.prepschedule',
  );
}
